Repository suraj-singh12/Project-SearchEverywhere, pull requests merged in 2021-10, with the labels that each got.

#3 add doc/docx extension support
  src/SearchEverywhere.py
Labels: enhancement, hacktoberfest, hacktoberfest2k21

#4 Fedora dependencies
  dependencies.sh
  fedoradep.sh
Labels: documentation, hacktoberfest, hacktoberfest2k21

#7 Add ppt/pptx support
  src/SearchEverywhere.py
Labels: enhancement, hacktoberfest, hacktoberfest2k21

#9 dependencies updated for arch-based void-Linux debian-based
  dependency.sh
  install.sh
Labels: enhancement, hacktoberfest, hacktoberfest2k21

#10 removed non required dep files, and updated uninstall.sh
  debiandep.sh
  fedoradep.sh
  uninstall.sh
Labels: documentation, hacktoberfest, hacktoberfest2k21, hacktoberfest-accepted
